"""u11_manual_resolution_request

Revision ID: 14fa94a1e5ef
Revises: 0015
Create Date: 2026-09-18 09:09:28.874527
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14fa94a1e5ef'
down_revision: Union[str, None] = '0015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_resolution_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=200), nullable=False),
    sa.Column('field_label', sa.String(length=200), nullable=True),
    sa.Column('field_role', sa.String(length=100), nullable=True),
    sa.Column('candidate_value', sa.String(length=500), nullable=True),
    sa.Column('available_options', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolved_value', sa.String(length=500), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manual_resolution_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_resolution_requests_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manual_resolution_requests_opportunity_id'), ['opportunity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_resolution_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_resolution_requests_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_manual_resolution_requests_application_id'))

    op.drop_table('manual_resolution_requests')
    # ### end Alembic commands ###
